[project]
name = "trading23-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.2",
    "pandas-stubs>=2.2.3.241009",
    "pandas>=2.2.3",
    "polars>=1.12.0",
    "pydantic>=2.9.2",
    "requests>=2.32.3",
    "typer>=0.13.0",
    "types-requests>=2.32.0.20241016",
]
