DB_PATH = "./data/trading23_ml.sqlite"
APP_SETTINGS_PATH = "./app_settings.json"
NIKKEI225_PATH = "./data/nikkei225.csv"
TOPIX400_PATH = "./data/topix400.csv"
SHORT_PROGRESS_BAR = "{l_bar}{bar:10}{r_bar}{bar:-10b}"
